### PR TITLE
updates luigi to 2.0.0

### PR DESCRIPTION
**Pull request by mickelsonm**
updates to luigi 2.0.0 - much prettier UI! :smirk:

### CODE REVIEW

**Comment by tedder** [comment]
@mickelsonm are you building your v2 image on Dockerhub?

**Comment by mickelsonm** [comment]
@tedder nope...present not building it on Dockerhub.

**Comment by tedder** [comment]
@mickelsonm okay. I stole your fork and am modifying it- I'll probably go to a non-phusion base and make sure I can override things easily.

**Comment by mickelsonm** [comment]
@tedder nice! i'll definitely be keeping an eye out for it!

**Pull request merged**
